[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[net]
git-fetch-with-cli = true

[alias]
xtask = "run --package xtask -- "
make = "xtask"